# fly.toml app configuration file generated for rest-api-utilities-data-management-project on 2025-05-26T19:07:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rest-api-utilities-data-management-project'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
